### ISSUE TITLE
No POM file blocks Maven installation

### ISSUE THREAD

**Issue by SFSailor** [danwild/wind-js-server#4]
I'm new to Maven, but trying to install wind-js-server on Linux/nginx server fails with error:
"The goal you specified requires a project to execute but there is no POM in this directory"

I've looked through the distribution and found no POM file.  Did I miss it? Is it not needed?  Thanks for tolerating a noob question.

**Comment by danwild** [comment]
Hi @SFSailor, there is no POM file because this is a *NodeJS* server application, not Java (the underlying `grib2json` converter is indeed written in Java, however the point of this project was to provide a simple nodejs wrapper on top to support simple REST requests).

So to install this app:

1. Install [NodeJS](https://nodejs.org) (comes with [npm](https://www.npmjs.com))
2. Use npm to install project dependencies by calling `npm install` in the project root
2. Use node to run the application by calling `node app.js` in the project root

**Comment by SFSailor** [comment]
Thank you.  I was reading the wrong readMe.
